package com.motogp.model.entities.ENUMS;

public enum Posicion {
    
ZERO, PRIMERO,SEGUNDO, TERCERO, CUARTO, QUINTO, SEXTO, SÉPTIMO, OCTAVO, NOVENO, DÉCIMO, UNDÉCIMO, DUODÉCIMO, DECIMOTERCERO, DECIMOCUARTO, DECIMOQUINTO, DECIMOSEXTO, DECIMOSÉPTIMO, DECIMOCTAVO, DECIMONOVENO, VIGÉSIMO, VIGÉSIMO_PRIMERO, VIGÉSIMO_SEGUNDO, VIGÉSIMO_TERCERO


}
